fix(dde-osd): 修复玲珑应用通知无法跳转
linuxdeepin/dde-session-ui pull request #324
Opened 2023-03-08 02:50 UTC by kamiyadm

通过应用对应desktop文件启动应用
linuxdeepin/developer-center#3657

2023-03-29 11:15 UTC, BLumia requested changes

2023-03-29 11:15 UTC, BLumia commented on dde-osd/src/notification/bubbletool.cpp
> +            }
这部分的格式（`QStringList{ d`）与缩进（`if`）。

2023-03-30 01:45 UTC, kamiyadm commented on dde-osd/src/notification/bubbletool.cpp
> +            }
ok, 已经调了

2023-03-30 01:59 UTC, BLumia approved these changes

2023-03-30 01:59 UTC, BLumia commented
/merge

2023-03-30 01:59 UTC, merged